/////////////////////////////////////////////////////////////////////////////
// Name:        MediaCtrl.cpp
// Purpose:     
// Author:      0Cool
// Modified by: 
// Created:     Mon 15 Jan 2007 16:12:46 CET
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Mon 15 Jan 2007 16:12:46 CET

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "MediaCtrl.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "MediaCtrl.h"

////@begin XPM images
////@end XPM images

/*!
 * MediaCtrl type definition
 */

IMPLEMENT_CLASS( MediaCtrl, wxFrame )

/*!
 * MediaCtrl event table definition
 */

BEGIN_EVENT_TABLE( MediaCtrl, wxFrame )

////@begin MediaCtrl event table entries
////@end MediaCtrl event table entries

END_EVENT_TABLE()

/*!
 * MediaCtrl constructors
 */

MediaCtrl::MediaCtrl( )
{
    Init();
}

MediaCtrl::MediaCtrl( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create( parent, id, caption, pos, size, style );
}

/*!
 * MediaCtrl creator
 */

bool MediaCtrl::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin MediaCtrl creation
    wxFrame::Create( parent, id, caption, pos, size, style );

    CreateControls();
    Centre();
////@end MediaCtrl creation
    return true;
}

/*!
 * Member initialisation 
 */

void MediaCtrl::Init()
{
////@begin MediaCtrl member initialisation
////@end MediaCtrl member initialisation
}
/*!
 * Control creation for MediaCtrl
 */

void MediaCtrl::CreateControls()
{    
////@begin MediaCtrl content construction
    MediaCtrl* itemFrame1 = this;

    wxPanel* itemPanel2 = new wxPanel( itemFrame1, ID_PANEL1, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL );

    wxBoxSizer* itemBoxSizer3 = new wxBoxSizer(wxVERTICAL);
    itemPanel2->SetSizer(itemBoxSizer3);

    wxBoxSizer* itemBoxSizer4 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer3->Add(itemBoxSizer4, 0, 0, 0);

    wxButton* itemButton5 = new wxButton( itemPanel2, ID_BUTTON1, _("|<"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer4->Add(itemButton5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton6 = new wxButton( itemPanel2, ID_BUTTON3, _("Button"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer4->Add(itemButton6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton7 = new wxButton( itemPanel2, ID_BUTTON4, _("Button"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer4->Add(itemButton7, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton8 = new wxButton( itemPanel2, ID_BUTTON2, _("Button"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer4->Add(itemButton8, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton9 = new wxButton( itemPanel2, ID_BUTTON5, _("Button"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer4->Add(itemButton9, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxSlider* itemSlider10 = new wxSlider( itemPanel2, ID_SLIDER1, 0, 0, 100, wxDefaultPosition, wxDefaultSize, wxSL_HORIZONTAL );
    itemBoxSizer3->Add(itemSlider10, 0, wxGROW|wxALL|wxFIXED_MINSIZE, 5);

////@end MediaCtrl content construction

    // Create custom windows not generated automatically here.
////@begin MediaCtrl content initialisation
////@end MediaCtrl content initialisation
}

/*!
 * Should we show tooltips?
 */

bool MediaCtrl::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap MediaCtrl::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin MediaCtrl bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end MediaCtrl bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon MediaCtrl::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin MediaCtrl icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end MediaCtrl icon retrieval
}
