/////////////////////////////////////////////////////////////////////////////
// Name:        MediaCtrl.h
// Purpose:     
// Author:      0Cool
// Modified by: 
// Created:     Mon 15 Jan 2007 16:12:46 CET
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Mon 15 Jan 2007 16:12:46 CET

#ifndef _MediaCtrl_H_
#define _MediaCtrl_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "MediaCtrl.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/frame.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_MediaCtrl 10005
#define ID_PANEL1 10006
#define ID_BUTTON1 10001
#define ID_BUTTON3 10003
#define ID_BUTTON4 10004
#define ID_BUTTON2 10002
#define ID_BUTTON5 10008
#define ID_SLIDER1 10007
#define SYMBOL_MediaCtrl_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_MediaCtrl_TITLE _("Dialog")
#define SYMBOL_MediaCtrl_IDNAME ID_MediaCtrl
#define SYMBOL_MediaCtrl_SIZE wxSize(400, 300)
#define SYMBOL_MediaCtrl_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * MediaCtrl class declaration
 */

class MediaCtrl: public wxFrame
{    
    DECLARE_CLASS( MediaCtrl )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    MediaCtrl( );
    MediaCtrl( wxWindow* parent, wxWindowID id = SYMBOL_MediaCtrl_IDNAME, const wxString& caption = SYMBOL_MediaCtrl_TITLE, const wxPoint& pos = SYMBOL_MediaCtrl_POSITION, const wxSize& size = SYMBOL_MediaCtrl_SIZE, long style = SYMBOL_MediaCtrl_STYLE );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_MediaCtrl_IDNAME, const wxString& caption = SYMBOL_MediaCtrl_TITLE, const wxPoint& pos = SYMBOL_MediaCtrl_POSITION, const wxSize& size = SYMBOL_MediaCtrl_SIZE, long style = SYMBOL_MediaCtrl_STYLE );

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin MediaCtrl event handler declarations

////@end MediaCtrl event handler declarations

////@begin MediaCtrl member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end MediaCtrl member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin MediaCtrl member variables
////@end MediaCtrl member variables
};

#endif
    // _MediaCtrl_H_
