// -*- C++ -*- generated by wxGlade 0.4cvs on Thu Jun 22 12:57:19 2006

#include <wx/wx.h>
#include <wx/image.h>
#include "HIFrame.h"
#include"Panels/HIGridPanel.h"
#include<debug.h>

    

class HIApp:public wxApp {
  public:
    bool OnInit();
    ~HIApp() {
	DEBOUT(("HIApp()::~HIApp()\n"));
    };
};

IMPLEMENT_APP(HIApp)



bool HIApp::OnInit()
{
    //wxInitAllImageHandlers();

    try {
      DEBOUT(("DisplaySize %dx%d\n",wxGetDisplaySize().GetWidth(),wxGetDisplaySize().GetHeight()));
      wxSize size = wxGetDisplaySize();
	HIFrame *hiframe =new HIFrame(NULL, wxID_ANY, wxT("Calibrate Frame"),wxPoint(0,0),wxGetDisplaySize());
//       HIGridPanel* hiframe = new HIGridPanel(NULL, wxID_ANY,wxDefaultPosition);
//       hiframe->setText(0,0,"506");
     
      
      
//       MediaCtrl* hiframe = new MediaCtrl(NULL, wxID_ANY, _("HOLA"), wxDefaultPosition, wxDefaultSize, wxDEFAULT_FRAME_STYLE);
//       wxBoxSizer* sizer_frame = new  wxBoxSizer(wxHORIZONTAL);
//       hiframe ->SetSizer(sizer_frame);
      
//       HIMediaCtrl* media = new HIMediaCtrl(hiframe,wxID_ANY,wxDefaultPosition, hiframe->GetSize());
// 	
//       sizer_frame->Add(media,  0, wxALIGN_CENTER_VERTICAL|wxALL, 5);
      
      
	SetTopWindow(hiframe);
	hiframe->Show();
	
// 	hiframe->resizeRows(7);
	
	return true;
    }
    catch(runtime_error e) {
	wxLogError(wxString(e.what(), wxConvUTF8));
    }
    return false;
}
